#!/bin/sh
# COMMENT: #SBATCH directives that convey submission options:
#SBATCH --job-name=testing_cuda
#SBATCH --mail-user=chrireed@umich.edu
#SBATCH --mail-type=BEGIN,END
#SBATCH --cpus-per-task=1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --mem-per-cpu=1000m
#SBATCH --time=00-00:01:00
#SBATCH --account=eecs570s001w25_class
#SBATCH --partition=gpu
#SBATCH --gpus-per-node=1
#SBATCH --output=/scratch/eecs570s001w25_class_root/eecs570s001w25_class/chrireed/DPX_GPU_Genomics_Project/logs/%x-%j.log
#SBATCH --error=/scratch/eecs570s001w25_class_root/eecs570s001w25_class/chrireed/DPX_GPU_Genomics_Project/logs/error-%x-%j.log
# COMMENT:The application(s) to execute along with its input arguments and options:
./test